# N.B.!! This is the config for the legacy readthedocs site.
# All of the docs pages have been removed from the source, and Page Redirects
# have been setup in the RTD admin console. This means that all rubocop.readthedocs.io
# links should be redirected to their corresponding docs page at docs.rubocop.org.
site_name: "RuboCop: The Ruby Linter that Serves and Protects"
repo_url: https://github.com/zspencer/rbhint
edit_uri: edit/master/legacy-docs/
copyright: "Copyright &copy; 2012-2020 Bozhidar Batsov and RuboCop contributors"
docs_dir: legacy-docs
theme: readthedocs
